/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIntegrationsModernizationRouteImport } from './routes/services_.integrations-modernization'
import { Route as IndustriesRetailOmnichannelCommerceRouteImport } from './routes/industries.retail-omnichannel-commerce'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIntegrationsModernizationRoute =
  ServicesIntegrationsModernizationRouteImport.update({
    id: '/services_/integrations-modernization',
    path: '/services/integrations-modernization',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesRetailOmnichannelCommerceRoute =
  IndustriesRetailOmnichannelCommerceRouteImport.update({
    id: '/industries/retail-omnichannel-commerce',
    path: '/industries/retail-omnichannel-commerce',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/services': typeof ServicesRoute
  '/industries/retail-omnichannel-commerce': typeof IndustriesRetailOmnichannelCommerceRoute
  '/services/integrations-modernization': typeof ServicesIntegrationsModernizationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/services': typeof ServicesRoute
  '/industries/retail-omnichannel-commerce': typeof IndustriesRetailOmnichannelCommerceRoute
  '/services/integrations-modernization': typeof ServicesIntegrationsModernizationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/services': typeof ServicesRoute
  '/industries/retail-omnichannel-commerce': typeof IndustriesRetailOmnichannelCommerceRoute
  '/services_/integrations-modernization': typeof ServicesIntegrationsModernizationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/services'
    | '/industries/retail-omnichannel-commerce'
    | '/services/integrations-modernization'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/services'
    | '/industries/retail-omnichannel-commerce'
    | '/services/integrations-modernization'
  id:
    | '__root__'
    | '/'
    | '/services'
    | '/industries/retail-omnichannel-commerce'
    | '/services_/integrations-modernization'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServicesRoute: typeof ServicesRoute
  IndustriesRetailOmnichannelCommerceRoute: typeof IndustriesRetailOmnichannelCommerceRoute
  ServicesIntegrationsModernizationRoute: typeof ServicesIntegrationsModernizationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/integrations-modernization': {
      id: '/services_/integrations-modernization'
      path: '/services/integrations-modernization'
      fullPath: '/services/integrations-modernization'
      preLoaderRoute: typeof ServicesIntegrationsModernizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/retail-omnichannel-commerce': {
      id: '/industries/retail-omnichannel-commerce'
      path: '/industries/retail-omnichannel-commerce'
      fullPath: '/industries/retail-omnichannel-commerce'
      preLoaderRoute: typeof IndustriesRetailOmnichannelCommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServicesRoute: ServicesRoute,
  IndustriesRetailOmnichannelCommerceRoute:
    IndustriesRetailOmnichannelCommerceRoute,
  ServicesIntegrationsModernizationRoute:
    ServicesIntegrationsModernizationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
