/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndustriesRetailOmnichannelCommerceRouteImport } from './routes/industries.retail-omnichannel-commerce'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRetailOmnichannelCommerceRoute =
  IndustriesRetailOmnichannelCommerceRouteImport.update({
    id: '/industries/retail-omnichannel-commerce',
    path: '/industries/retail-omnichannel-commerce',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/industries/retail-omnichannel-commerce': typeof IndustriesRetailOmnichannelCommerceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/industries/retail-omnichannel-commerce': typeof IndustriesRetailOmnichannelCommerceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/industries/retail-omnichannel-commerce': typeof IndustriesRetailOmnichannelCommerceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/industries/retail-omnichannel-commerce'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/industries/retail-omnichannel-commerce'
  id: '__root__' | '/' | '/industries/retail-omnichannel-commerce'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndustriesRetailOmnichannelCommerceRoute: typeof IndustriesRetailOmnichannelCommerceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/retail-omnichannel-commerce': {
      id: '/industries/retail-omnichannel-commerce'
      path: '/industries/retail-omnichannel-commerce'
      fullPath: '/industries/retail-omnichannel-commerce'
      preLoaderRoute: typeof IndustriesRetailOmnichannelCommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndustriesRetailOmnichannelCommerceRoute:
    IndustriesRetailOmnichannelCommerceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
